### ISSUE TITLE
case block is parsed beyond end

### ISSUE THREAD

**Issue by kopischke** [mkhl/bash.sugar#1]
The parser  misses `case` block ends. `esac` is not caught as a keyword, block highlighting and navigator indentation indicate the block is parsed as if continuing until the script's end. Syntax inspector reveals a spurious `container.block.case-clause` is found after the last real clause. [OT: otherwise great sugar, love it].

**Comment by mkhl** [comment]
Could you gist an example where it misses the `esac`?
The sugar also includes a bunch of simple syntax tests in `Tests/syntax-test.sh`. Is the `case` block (ll. 137-156) parsed correctly for you?

Also, thanks for the feedback. Glad you like it :-)

**Comment by mkhl** [comment]
Fix parser error for indented `esac` keywords.

Espresso’s parser engine has many subtle differences from TextMate’s; this is
one of them, where it seems like (zero-width positive) lookaheads without
parser state can only lookahead from the beginning of the line.

Closed by 43a842bee51454f4bff17358675686f78f83dd91

**Comment by mkhl** [comment]
Could you update to `43a842b` (or later) and see if it works for you?
At least the gisted scripts seems to parse correctly now.

**Comment by kopischke** [comment]
Correct parsing of `case` statements in my bash scripts confirmed. Thanks for fixing this!
