### ISSUE TITLE
PHP code completion leaks into bash sugar

### ISSUE THREAD

**Issue by kopischke** [mkhl/bash.sugar#2]
Not sure which sugar causes the problem, so I am opening an issue on both: PHP code completion (form the official _PHP_ sugar at http://github.com/derekr/php.sugar/tree) is leaking into _bash_ scope (and only into this).

**Comment by mkhl** [comment]
Again, could you provide a simple example where this happens?
If the file it happens in includes here-documents (in shell script), could you try removing the `SyntaxInjections` folder from the bash sugar?

**Comment by mkhl** [comment]
As it’s not heredoc-related try this:
In PHP’s `CodeSenseProviders/PHP.xml` file, in the `codesense.provider.selector` item, prepend every top level item[1] with the string `php` (note the space behind the `php` and before the rest of the selector).

[1] The selector consists of a lot of clauses of the form `identifier.method > \*:not(...)`; these should then read `php identifier.method > \*:not(...)` instead. The first clause has a php-specific selector already (`container.block.embedded.source.php`) and should **not** be changed.

**Comment by kopischke** [comment]
The problem has gone away with Syntax Injections disabled in the bash sugar's most recent commit. I haven't had time to try out the solution outlined above (yet – I can see if I manage to this weekend, if you like). Should we report the above solution proposal to the PHP sugar maintainer?

**Comment by mkhl** [comment]
Hm, no, don’t bother trying that solution. If the missing syntax injections took care of the problem, I’ll assume it’s my fault, and I never got the injections working properly in the first place.
Once I understand how to do the here-doc injections properly, if the problem reappears, we can still reopen the issue and start poking Derek.

Could you still gist me a file where you were able to observe the leaking PHP completions? I’m curious how it could be triggered without any here-docs present, and with a broken selector to begin with…
(If it’s a work-related project and you don’t want it publicly visible, you can use a private gist and message me the URL. If it would be too much effort to anonymize a complete test case, feel free not to do it, I’ll cope ;-)

**Comment by mkhl** [comment]
Oh, just for Management:
Fixed in fb0239f.

**Comment by kopischke** [comment]
Actually, the gist I sent you for the case parsing issue did exhibit that behaviour: http://gist.github.com/114237

**Comment by mkhl** [comment]
Ah, I see. If you remember, did it do that anywhere in the file or in specific places? I’ll try to reproduce it here.

**Comment by kopischke** [comment]
I seem to remember it happened _inside_ the function block. Couldn't swear to it, tho.

**Comment by mkhl** [comment]
Thanks, I’ll take a look.
