### ISSUE TITLE
Feature proposal: treat multiple comment lines as one token

### ISSUE THREAD

**Issue by kopischke** [mkhl/bash.sugar#3]
Bash does not have a multi-line comment syntax, which makes multiple `#` comment lines clutter up the navigator in Espresso rapidly, to the point of rendering it useless in heavily commented code (point in case: license sections). Would it be possible to tweak the bash sugar to tokenize multiple consecutive comment lines as one comment block?

**Comment by mkhl** [comment]
Should be fixed in c0bfb979.

**Comment by kopischke** [comment]
Yay! That was fast. Love how the navigator suddenly is useful for something again.
