### ISSUE TITLE
Display command block keywords in navigator

### ISSUE THREAD

**Issue by kopischke** [mkhl/bash.sugar#4]
Unlike with functions, where it displays the function name, the navigator only displays a generic `{...}` for command blocks (`if`, `case`, `while` etc.). Displaying the clause itself (i.e. `if {...}`) would ease navigation; better even if the condition was displayed too (i.e. `if: -n "$0"`).

**Comment by mkhl** [comment]
I believe this is fixed in 3f43c4a. Could you try that out?
Check the Downloads tab if you’d like a pre-built version.

**Comment by kopischke** [comment]
Confirmed, sweet and nice. Thank you!
