### ISSUE TITLE
Keep code block keyword visible on folding

### ISSUE THREAD

**Issue by kopischke** [mkhl/bash.sugar#5]
Folding a function or command block hides all of the block, making folding of limited use as the content vanishes entirely from sight. Keeping the keyword part visible (i.e. `function foo ...` or `if [-n "$0"] ...`, as the PHP sugar does) would improve the usability of code folding.

**Comment by mkhl** [comment]
I took a look at the PHP sugar, and it accomplishes this effect by leaving the keyword out of the itemizer.
I think this is the wrong way to go, and would be harder to pull off with bash syntax, so I’ll have to look for another way.

**Comment by mkhl** [comment]
I haven’t found a way to modify this behaviour at the Itemizer level. I’ll try a few more things, but we might have to wait for an Espresso update to provide this.
